import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Header } from '../../components/Header';
import { Screen } from '../../components/Screen';
import { Card } from '../../components/Card';
import { colors } from '../../constants/theme';
import { useResident } from '../../lib/resident-context';
export default function MakePayment(){const {billId}=useLocalSearchParams<{billId?:string}>();const {bills}=useResident();const bill=useMemo(()=>bills.find(b=>b.$id===billId)||bills.find(b=>b.balanceDue>0)||bills[0],[billId,bills]);const [method,setMethod]=useState('EcoCash');const [note,setNote]=useState('');return <View style={styles.root}><Header title="Make Payment" back/><Screen><Text style={styles.section}>Select Bill</Text><Card><Text style={styles.select}>{bill.billNumber} - {bill.description}</Text></Card><Card style={{marginTop:10}}><Info label="Amount Due" value={`$${bill.balanceDue.toFixed(2)}`} green/><Info label="Total Amount" value={`$${Math.max(bill.balanceDue,bill.amount).toFixed(2)}`}/></Card><Text style={styles.section}>Payment Method</Text><Card>{['EcoCash','Cash','Bank Transfer'].map(x=><TouchableOpacity key={x} style={styles.method} onPress={()=>setMethod(x)}><Ionicons name={method===x?'radio-button-on':'radio-button-off'} size={20} color={method===x?colors.blue:colors.text}/><View><Text style={styles.methodTitle}>{x}</Text><Text style={styles.methodSub}>{x==='EcoCash'?'Mobile Money':x==='Cash'?'Pay at council office':'Direct to council account'}</Text></View></TouchableOpacity>)}</Card><Text style={styles.section}>Notes (optional)</Text><TextInput value={note} onChangeText={setNote} placeholder="Add a note..." style={styles.input} multiline/><TouchableOpacity style={styles.pay} onPress={()=>Alert.alert('Payment', 'Payment request created for demonstration. Connect your payment gateway here.')}><Text style={styles.payText}>Pay ${Math.max(bill.balanceDue,bill.amount).toFixed(2)}</Text></TouchableOpacity></Screen></View>}
function Info({label,value,green}:{label:string,value:string,green?:boolean}){return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={[styles.value,green&&{color:colors.green}]}>{value}</Text></View>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:colors.background},section:{fontSize:12,fontWeight:'900',color:colors.text,marginTop:12,marginBottom:7},select:{fontSize:11,color:colors.text,fontWeight:'700'},info:{flexDirection:'row',justifyContent:'space-between',paddingVertical:5},label:{fontSize:10,color:colors.text},value:{fontSize:12,fontWeight:'900',color:colors.text},method:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:11,borderBottomWidth:1,borderBottomColor:colors.border},methodTitle:{fontSize:11,fontWeight:'800'},methodSub:{fontSize:9,color:colors.muted,marginTop:2},input:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:10,minHeight:58,padding:12,textAlignVertical:'top',fontSize:11},pay:{height:48,backgroundColor:colors.blue,borderRadius:9,alignItems:'center',justifyContent:'center',marginTop:16},payText:{color:colors.white,fontWeight:'900',fontSize:13}});
