import { router } from 'expo-router';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Card } from '../../components/Card';
import { Screen } from '../../components/Screen';
import { StatusPill } from '../../components/StatusPill';
import { Header } from '../../components/Header';
import { colors } from '../../constants/theme';
import { useResident } from '../../lib/resident-context';

const money = (n:number)=>`$${n.toFixed(2)}`;
export default function Bills(){ const {bills}=useResident(); return <View style={styles.root}><Header title="Bills"/><View style={styles.tabs}><Text style={[styles.tab,styles.active]}>All</Text><Text style={styles.tab}>Unpaid</Text><Text style={styles.tab}>Paid</Text></View><Screen>{bills.map(b=><Card key={b.$id} style={styles.bill}><View style={styles.row}><View style={styles.billIcon}>▦</View><View style={styles.titleWrap}><Text style={styles.title}>{b.description}</Text><Text style={styles.meta}>{b.billNumber} · {b.revenueSourceId}</Text></View><StatusPill value={b.status}/></View><View style={styles.stats}><Stat label="Amount" value={money(b.amount)}/><Stat label="Paid" value={money(b.amountPaid)}/><Stat label="Balance" value={money(b.balanceDue)}/></View><View style={styles.dates}><View><Text style={styles.small}>Billing date</Text><Text style={styles.value}>{formatDate(b.billingDate)}</Text></View><View><Text style={styles.small}>Due date</Text><Text style={styles.value}>{formatDate(b.dueDate)}</Text></View></View><TouchableOpacity style={styles.details} onPress={()=>router.push({pathname:'/bills/[id]',params:{id:b.$id}})}><Text style={styles.detailsText}>View Details</Text></TouchableOpacity></Card>)}</Screen></View> }
function Stat({label,value}:{label:string,value:string}){return <View style={{flex:1}}><Text style={styles.small}>{label}</Text><Text style={styles.value}>{value}</Text></View>}
function formatDate(s:string){return new Date(s).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:colors.background},tabs:{height:42,backgroundColor:colors.white,borderBottomWidth:1,borderBottomColor:colors.border,flexDirection:'row',justifyContent:'space-around',alignItems:'center'},tab:{width:'33%',textAlign:'center',fontSize:11,color:colors.text,paddingVertical:12},active:{color:colors.blue,fontWeight:'900',borderBottomWidth:2,borderBottomColor:colors.blue},bill:{marginBottom:12},row:{flexDirection:'row',alignItems:'center',gap:9},billIcon:{width:34,height:34,borderRadius:17,backgroundColor:colors.blue,color:colors.white,textAlign:'center',textAlignVertical:'center',fontSize:19},titleWrap:{flex:1},title:{fontSize:12,fontWeight:'900',color:colors.text},meta:{fontSize:9,color:colors.muted,marginTop:3},stats:{flexDirection:'row',borderTopWidth:1,borderBottomWidth:1,borderColor:colors.border,paddingVertical:10,marginTop:10},small:{fontSize:9,color:colors.muted},value:{fontSize:11,fontWeight:'800',color:colors.text,marginTop:3},dates:{flexDirection:'row',justifyContent:'space-between;paddingVertical:9},details:{height:36,borderWidth:1,borderColor:colors.border,borderRadius:9,alignItems:'center',justifyContent:'center'},detailsText:{fontSize:11,color:colors.navy,fontWeight:'900'}});
