import { router } from 'expo-router';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Card } from '../../components/Card';
import { Header } from '../../components/Header';
import { Screen } from '../../components/Screen';
import { colors } from '../../constants/theme';
import { useResident } from '../../lib/resident-context';
export default function Profile(){const {resident}=useResident();return <View style={styles.root}><Header title="Profile"/><Screen><Card><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>{resident.firstName[0]}{resident.lastName[0]}</Text></View><View><Text style={styles.name}>{resident.firstName} {resident.lastName}</Text><Text style={styles.email}>{resident.email}</Text><Text style={styles.phone}>{resident.phone}</Text></View></View></Card><Text style={styles.section}>Personal Information</Text><Card>{[['National ID',resident.nationalId],['Address',resident.address],['Ward',resident.ward],['Property Number',resident.propertyNumber]].map(([k,v])=><View style={styles.info} key={k}><Text style={styles.label}>{k}</Text><Text style={styles.value}>{v}</Text></View>)}</Card><TouchableOpacity style={styles.rowAction}><Text style={styles.rowText}>Update Profile</Text><Text style={styles.chev}>›</Text></TouchableOpacity><TouchableOpacity style={styles.rowAction} onPress={()=>router.push('/settings')}><Text style={styles.rowText}>Change Password</Text><Text style={styles.chev}>›</Text></TouchableOpacity></Screen></View>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:colors.background},profile:{flexDirection:'row',alignItems:'center'},avatar:{width:52,height:52,borderRadius:26,backgroundColor:colors.blue,alignItems:'center',justifyContent:'center',marginRight:12},avatarText:{color:colors.white,fontWeight:'900',fontSize:18},name:{fontSize:14,fontWeight:'900',color:colors.text},email:{fontSize:9,color:colors.text,marginTop:3},phone:{fontSize:9,color:colors.muted,marginTop:3},section:{fontSize:12,fontWeight:'900',color:colors.text,marginTop:18,marginBottom:8},info:{flexDirection:'row',justifyContent:'space-between',paddingVertical:10,borderBottomWidth:1,borderBottomColor:colors.border},label:{fontSize:10,color:colors.text},value:{fontSize:10,fontWeight:'700',color:colors.muted,maxWidth:'58%',textAlign:'right'},rowAction:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:10,padding:13,marginTop:9,flexDirection:'row',justifyContent:'space-between'},rowText:{fontSize:11,fontWeight:'800',color:colors.text},chev:{fontSize:20,color:colors.muted}});
