import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Card } from '../../components/Card';
import { Header } from '../../components/Header';
import { Screen } from '../../components/Screen';
import { StatusPill } from '../../components/StatusPill';
import { colors } from '../../constants/theme';
import { useResident } from '../../lib/resident-context';
export default function BillDetails(){const {id}=useLocalSearchParams<{id:string}>();const {bills,payments}=useResident();const b=bills.find(x=>x.$id===id)??bills[0];const p=payments.find(x=>x.billId===b.$id);return <View style={styles.root}><Header title="Bill Details" back/><Screen><Card><View style={styles.row}><View style={styles.icon}><Ionicons name="business" size={20} color={colors.white}/></View><View style={{flex:1}}><Text style={styles.title}>{b.description}</Text><Text style={styles.meta}>{b.billNumber} · {b.revenueSourceId}</Text></View><StatusPill value={b.status}/></View><View style={styles.line}/><Info label="Description" value={b.description}/><Info label="Amount" value={`$${b.amount.toFixed(2)}`}/><Info label="Amount Paid" value={`$${b.amountPaid.toFixed(2)}`}/><Info label="Balance Due" value={`$${b.balanceDue.toFixed(2)}`} green/><Info label="Billing Date" value={fmt(b.billingDate)}/><Info label="Due Date" value={fmt(b.dueDate)}/><Info label="Status" value={b.status}/></Card>{p&&<Card style={{marginTop:12}}><Text style={styles.section}>Payment</Text><View style={styles.row}><Ionicons name="checkmark-circle" size={24} color={colors.green}/><View style={{flex:1,marginLeft:9}}><Text style={styles.title}>{p.paymentReference}</Text><Text style={styles.meta}>{p.paymentMethod} · {fmt(p.paymentDate)}</Text></View><Text style={styles.value}>${p.amount.toFixed(2)}</Text></View></Card>}<TouchableOpacity style={styles.download}><Ionicons name="download-outline" size={17} color={colors.blue}/><Text style={styles.downloadText}>Download Bill</Text></TouchableOpacity>{b.balanceDue>0&&<TouchableOpacity style={styles.pay} onPress={()=>router.push({pathname:'/payments/make',params:{billId:b.$id}})}><Text style={styles.payText}>Pay ${b.balanceDue.toFixed(2)}</Text></TouchableOpacity>}</Screen></View>}
function Info({label,value,green}:{label:string,value:string,green?:boolean}){return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={[styles.value,green&&{color:colors.green}]}>{value}</Text></View>}
const fmt=(s:string)=>new Date(s).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});
const styles=StyleSheet.create({root:{flex:1,backgroundColor:colors.background},row:{flexDirection:'row',alignItems:'center'},icon:{width:38,height:38,borderRadius:19,backgroundColor:colors.blue,alignItems:'center',justifyContent:'center',marginRight:9},title:{fontSize:12,fontWeight:'900',color:colors.text},meta:{fontSize:9,color:colors.muted,marginTop:3},line:{height:1,backgroundColor:colors.border,marginVertical:12},info:{flexDirection:'row',justifyContent:'space-between',paddingVertical:6},label:{fontSize:10,color:colors.text},value:{fontSize:11,fontWeight:'800',color:colors.text},section:{fontSize:13,fontWeight:'900',marginBottom:10,color:colors.text},download:{height:44,borderWidth:1,borderColor:colors.blue,borderRadius:9,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:6,marginTop:18},downloadText:{color:colors.blue,fontWeight:'900',fontSize:12},pay:{height:48,backgroundColor:colors.blue,borderRadius:9,alignItems:'center',justifyContent:'center',marginTop:10},payText:{color:colors.white,fontWeight:'900',fontSize:13}});
